def pitch_values(pitch, at_bat_id):
    return [
        None # rowid
      , pitch['description']
      , pitch['cc']
      , pitch['pitch_id']
      , pitch['timestamp']
      , pitch['pitch_type']
      , pitch['type_confidence']
      , pitch['zone']
      , pitch['nasty']
      , pitch['result']
      , pitch['x']
      , pitch['y']
      , pitch['start_speed']
      , pitch['end_speed']
      , pitch['pfx_x']
      , pitch['pfx_z']
      , pitch['px']
      , pitch['pz']
      , pitch['sv_id']
      , pitch['x0']
      , pitch['y0']
      , pitch['z0']
      , pitch['vx0']
      , pitch['vy0']
      , pitch['vz0']
      , pitch['ax']
      , pitch['ay']
      , pitch['az']
      , pitch['spin_dir']
      , pitch['spin_rate']
      , pitch['break_y']
      , pitch['break_angle']
      , pitch['break_length']
      , at_bat_id # at_bat rowid
    ]
